-- Raw order line items.
-- Lands in JAFFLE_SHOP.RAW.RAW_ITEMS.
-- DO NOT TRANSLATE: source table only.
CREATE OR REPLACE TABLE JAFFLE_SHOP.RAW.RAW_ITEMS (
    ID         VARCHAR(36)  NOT NULL,
    ORDER_ID   VARCHAR(36)  NOT NULL,   -- FK to RAW_ORDERS.ID
    SKU        VARCHAR(20)  NOT NULL    -- FK to RAW_PRODUCTS.SKU
);
