-- Mart: per-customer lifetime metrics — total orders, first/last ordered_at,
-- lifetime spend / tax / cost.
--
-- Translates to: models/marts/customers.sql
--   - ref('stg_customers'), ref('orders') (the marts model from orders_summary)
CREATE OR REPLACE TABLE JAFFLE_SHOP.LEGACY_PUBLIC.CUSTOMERS_SUMMARY AS
WITH
CUSTOMER_ORDERS_SUMMARY AS (
    SELECT
        CUSTOMER_ID,
        COUNT(DISTINCT ORDER_ID)             AS COUNT_LIFETIME_ORDERS,
        CASE WHEN COUNT(DISTINCT ORDER_ID) > 1 THEN TRUE ELSE FALSE END AS IS_REPEAT_BUYER,
        MIN(ORDERED_AT)                      AS FIRST_ORDERED_AT,
        MAX(ORDERED_AT)                      AS LAST_ORDERED_AT,
        SUM(SUBTOTAL)                        AS LIFETIME_SPEND_PRETAX,
        SUM(TAX_PAID)                        AS LIFETIME_TAX_PAID,
        SUM(ORDER_TOTAL)                     AS LIFETIME_SPEND
    FROM JAFFLE_SHOP.LEGACY_PUBLIC.ORDERS_SUMMARY
    GROUP BY CUSTOMER_ID
)
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    COALESCE(COS.COUNT_LIFETIME_ORDERS, 0)    AS COUNT_LIFETIME_ORDERS,
    COALESCE(COS.IS_REPEAT_BUYER, FALSE)      AS IS_REPEAT_BUYER,
    COS.FIRST_ORDERED_AT,
    COS.LAST_ORDERED_AT,
    COALESCE(COS.LIFETIME_SPEND_PRETAX, 0)    AS LIFETIME_SPEND_PRETAX,
    COALESCE(COS.LIFETIME_TAX_PAID, 0)        AS LIFETIME_TAX_PAID,
    COALESCE(COS.LIFETIME_SPEND, 0)           AS LIFETIME_SPEND
FROM JAFFLE_SHOP.LEGACY_PUBLIC.STG_CUSTOMERS C
LEFT JOIN CUSTOMER_ORDERS_SUMMARY COS ON COS.CUSTOMER_ID = C.CUSTOMER_ID;
