name: "jaffle_shop"
version: "1.0.0"
config-version: 2

profile: "jaffle_shop"

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  jaffle_shop:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
